// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api/config"
	"api/internal/database"
	"api/internal/handler"
	"api/internal/repository"
	"api/internal/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	config, err := loadConfig()
	if err != nil {
		return nil, err
	}
	mySQLConfig := provideMySQLConfig(config)
	db, err := database.NewMySQL(mySQLConfig)
	if err != nil {
		return nil, err
	}
	userRepo := repository.NewUserRepo(db)
	jwtConfig := provideJWTConfig(config)
	userService := service.NewUserService(userRepo, jwtConfig)
	userHandler := handler.NewUserHandler(userService)
	app := &App{
		DB:          db,
		Config:      config,
		UserHandler: userHandler,
	}
	return app, nil
}

// wire.go:

type App struct {
	DB          *gorm.DB
	Config      *config.Config
	UserHandler *handler.UserHandler
}

func loadConfig() (*config.Config, error) {
	return config.Load("config/config.yaml")
}

func provideMySQLConfig(cfg *config.Config) config.MySQLConfig {
	return cfg.MySQL
}

func provideJWTConfig(cfg *config.Config) *config.JWTConfig {
	return &cfg.JWT
}
